#! /bin/bash

# configs to be linked to the .config folder
programs=( qtile zathura kitty nvim starship mpv )

# configs
for program in "${programs[@]}"
do
    # removes folder if exists
    if [[ -e $CONF_FILES/$program ]]
    then
        rm -rf $CONF_FILES/$program
    fi

    # soft link to the repositories 
    ln -s $CONF_REPOS/$program $CONF_FILES/$program
    echo "created $program link"
done

# bashrc
if [[ -e $HOME/.bashrc ]]
then
    rm $HOME/.bashrc
fi
ln -s $SH_CONF/bashrc $HOME/.bashrc

# password store
if [[ -e $HOME/.password-store ]]
then
    rm -rf $HOME/.password-store
fi
ln -s $REPOS/pass/password_store $HOME/.password-store

# inputrc
if [[ -e $HOME/.inputrc ]]
then
    rm $HOME/.inputrc
fi
ln -s $SH_CONF/inputrc $HOME/.inputrc

# tmux
if [[ -e $HOME/.tmux.conf ]]
then
    rm $HOME/.tmux.conf
fi
ln -s $SH_CONF/tmux $HOME/.tmux.conf
